### ISSUE TITLE
Kanban Board Review - React Group Project

### ISSUE THREAD

**Issue by Luiscarlosvd** [Luiscarlosvd/space-travelers#46]
**_Link to the github project:_**  https://github.com/Luiscarlosvd/space-travelers

**We are a group of two people:** 
- **@Luiscarlosvd** 
- **@Alejuda**

**Comment by Lucas-Masaba** [comment]
# Hello @Luiscarlosvd 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Successfully used the project template provided to you :+1: 
- Tasks have been assigned to each other as required :+1: 
- Points have been balanced evenly to each other :balance_scale: 


## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
